In [1]:
# Tensor
# 데이터를 저장하는 다차원 배열 또는 컨테이너
# 딥러닝이 학습할때 사용하는 자료구조
# 0차원 텐서(스칼라) : 단일 데이터
# 1차원 텐서(벡터) : 리스트 형태  [1,2,3,4]
# 2차원 텐서(행렬) : 행 과 열로 이루어진 데이터 표데이터, 흑백 이미지(가로픽셀 x 세로픽셀)
# 3차원 텐서 : 컬러이미지 흑백이미지 + 채널정보(R G B)
# 고차원 텐서 : 동영상 : 이미지개수 x 가로픽셀 x 세로픽셀 x 채널정보

# 데이터의 표준 형식 : 일관된 숫자 형식
# 효율적인 계산 : GPU 지원 병열연산에 유리
# 딥러닝 프레임워크 : 텐서플로, 파이토치

In [2]:
# 기본연산
import torch
# 빈 텐서 생성
x = torch.empty(3,4)
x

tensor([[6.1663e-33, 1.0047e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [3]:
# 랜덤 텐서
torch.rand(3,4)

tensor([[0.1558, 0.5905, 0.7658, 0.4484],
        [0.9715, 0.3154, 0.7236, 0.9324],
        [0.7337, 0.5961, 0.9138, 0.1932]])

In [4]:
# 0으로 텐서 초기화
torch.zeros(3,4,dtype=torch.long)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [5]:
# 1로 채워진 텐서
torch.ones(3,4,dtype=torch.long)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [6]:
import numpy as np
# 토치와 넘파이 출력 형식 비교
print( torch.tensor( [3.5,3,2.1] ) )
print( np.array( [3.5,3,2.1] )  )

tensor([3.5000, 3.0000, 2.1000])
[3.5 3.  2.1]


In [7]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
y = torch.randn_like(x, dtype=torch.float)
x, y

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 0.0778, -0.0270,  0.3794, -0.9016],
         [ 1.9606, -1.3146,  1.1218, -0.5333],
         [ 0.4815, -0.5305,  0.4288,  0.7221]]))

In [8]:
# 덧셈

import torch
x=torch.rand(3,4)
y=torch.rand(3,4)

x,y, x+y

(tensor([[0.1082, 0.2663, 0.0209, 0.2137],
         [0.9538, 0.3237, 0.9271, 0.0681],
         [0.2336, 0.2084, 0.2473, 0.5279]]),
 tensor([[0.3895, 0.0660, 0.8827, 0.9907],
         [0.4291, 0.9096, 0.1665, 0.7282],
         [0.7533, 0.7359, 0.4439, 0.8622]]),
 tensor([[0.4977, 0.3323, 0.9036, 1.2044],
         [1.3829, 1.2333, 1.0936, 0.7963],
         [0.9869, 0.9443, 0.6912, 1.3901]]))

In [9]:
# 덧셈 함수로도 가능
torch.add(x,y)

tensor([[0.4977, 0.3323, 0.9036, 1.2044],
        [1.3829, 1.2333, 1.0936, 0.7963],
        [0.9869, 0.9443, 0.6912, 1.3901]])

In [10]:
# in-place y = y + x    y += x
y.add_(x)

tensor([[0.4977, 0.3323, 0.9036, 1.2044],
        [1.3829, 1.2333, 1.0936, 0.7963],
        [0.9869, 0.9443, 0.6912, 1.3901]])

In [11]:
# 행렬의 곱셉
x=torch.rand(3,4)
y=torch.rand(4,5)
x,y, torch.mm(x,y), x@y   # 파이썬 3.5부터 x@y 로도 표현 가능  # 다른차원의 곱셉은 (3,4) (4,5) --> 3x5

# ( x , y ) * ( x1, y1) 
# y, x1의 차수는 같아야 한다.


(tensor([[0.6802, 0.1221, 0.9261, 0.3867],
         [0.6009, 0.4117, 0.0353, 0.0222],
         [0.6677, 0.8944, 0.6818, 0.1897]]),
 tensor([[0.3353, 0.0056, 0.3072, 0.7002, 0.3001],
         [0.1113, 0.8334, 0.1005, 0.2861, 0.1092],
         [0.6821, 0.0197, 0.8119, 0.4933, 0.6710],
         [0.7454, 0.7749, 0.6399, 0.5201, 0.9173]]),
 tensor([[1.1615, 0.4235, 1.2206, 1.1692, 1.1935],
         [0.2880, 0.3644, 0.2689, 0.5675, 0.2694],
         [0.9298, 0.9096, 0.9699, 1.1584, 0.9295]]),
 tensor([[1.1615, 0.4235, 1.2206, 1.1692, 1.1935],
         [0.2880, 0.3644, 0.2689, 0.5675, 0.2694],
         [0.9298, 0.9096, 0.9699, 1.1584, 0.9295]]))

In [12]:
x = torch.tensor([1,2,3])
y = torch.tensor([1,2,3])
x*y

tensor([1, 4, 9])

In [13]:
# 슬라이싱 가능
x = torch.rand(4,5)
x, x[0,2:], x[1,1], x[1,1].item() ,type(x[1,1]), type(x[1,1].item())

# type(x[1,1].item())
# .item()은 0차원 스칼라 텐서를 파이썬 숫자(float) 로 변환합니다.


(tensor([[0.7599, 0.5352, 0.4319, 0.7149, 0.8741],
         [0.0980, 0.7131, 0.7705, 0.6458, 0.2930],
         [0.7966, 0.0403, 0.3847, 0.2206, 0.8750],
         [0.7851, 0.0260, 0.6489, 0.2264, 0.7498]]),
 tensor([0.4319, 0.7149, 0.8741]),
 tensor(0.7131),
 0.7131180763244629,
 torch.Tensor,
 float)

In [14]:
# 텐서크기 변경 reshape, view : nampy의 reshape와  동일한 기능
x=torch.rand(4,4)
y=x.view(16)     #변할 행렬이 이렇게 정해져있는 경우, -1로 하면 자동계산됨 (4x4 행렬이니 1로하려면 16밖에 안되므로.)
y_1=x.view(-1)
x,y, x.shape, y.shape, y_1, y_1.shape
#shape : 행렬 갯수 확인


(tensor([[0.1415, 0.0283, 0.4281, 0.5675],
         [0.1461, 0.9610, 0.6805, 0.4252],
         [0.6390, 0.9619, 0.5739, 0.6036],
         [0.7117, 0.8580, 0.1852, 0.6377]]),
 tensor([0.1415, 0.0283, 0.4281, 0.5675, 0.1461, 0.9610, 0.6805, 0.4252, 0.6390,
         0.9619, 0.5739, 0.6036, 0.7117, 0.8580, 0.1852, 0.6377]),
 torch.Size([4, 4]),
 torch.Size([16]),
 tensor([0.1415, 0.0283, 0.4281, 0.5675, 0.1461, 0.9610, 0.6805, 0.4252, 0.6390,
         0.9619, 0.5739, 0.6036, 0.7117, 0.8580, 0.1852, 0.6377]),
 torch.Size([16]))

In [15]:
# x 4 by 4
x.view(-1, 8)   #8을 줬기 때문에 무조건 2 x 8 행렬로만 reshape 가능하므로 -1을 주면 자동 계산해서 2x8로 reshape됨

tensor([[0.1415, 0.0283, 0.4281, 0.5675, 0.1461, 0.9610, 0.6805, 0.4252],
        [0.6390, 0.9619, 0.5739, 0.6036, 0.7117, 0.8580, 0.1852, 0.6377]])

In [16]:
# numpy - reshape는  torch - view #텐서모양 변경
# numpy - shape 는 torch - size  #텐서모양 확인
# 가독성. view, size 되었다는 것은 해당 자료구조가 텐서라는 것을 명시
x.size()

torch.Size([4, 4])

In [17]:
# 텐서 -> 넘파이
a = torch.ones(5)
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [18]:
# 넘파이 -> 텐서
a = np.array([1,2,3,4,5])
torch.from_numpy(a)

tensor([1, 2, 3, 4, 5])

In [19]:
# GPU 사용 (현재 노트북에서 불가능하므로 colab GPU 환경에서 실행해볼것)
# https://colab.research.google.com/drive/1UMkPAMg_gGDUfeMb3_YMeRBE63--Rw_z?usp=sharing
# torch.cuda.is_available() ==> 여기 노트북에서는 False
import torch
if torch.cuda.is_available():
    device = torch.device('cuda')   #GPU
    # 텐서들은 GPU에서 연산되기 때문에 생성을 GPU에서 생성
    x = torch.ones(5, device=device)  #GPU
    y = torch.ones(5) #CPU
    y = y.to(device)   #CPU -> GPU로 이용
    z = x+y
    print(f'GPU 연산결과 : {z}')
    print (f' 다시 CPU로 : {z.to("cpu", torch.double)}')
else:
    print('CUDA를 사용할 수 없습니다.')
    device = torch.device('cpu')

CUDA를 사용할 수 없습니다.


In [20]:
# 행렬의 곱
# ( x , y ) * ( x1, y1) 
# y, x1의 차수는 같아야 한다.
# 행렬곱의 결과의 모양(차수)은 x,y1 이 된다.

# 텐서는 딛러닝을 위해 만든 자료구조. 내부에 gpu 연산에 특화된 구조. 일반적인 모양은 넘파이와 동일. 
# 텐서는 GPU연산을 지원

In [21]:
# 자동 미분 (autograd) : 매 계산과정마다 계산과정의 미분값을 저장
# 파이토치 required_grad = True로 설정하면 : 계산그래프라는 형태로 기록 - 동영상녹화와 비슷한 원리
# .backword() 호출하면 이 과정을 거꾸로 되감으면서 각 단계의 미분값을 계산해 최종 기울기를 얻는다 

In [22]:
x = torch.ones(2,2, requires_grad=True)
x, x.size()

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True),
 torch.Size([2, 2]))

In [23]:
y = x + 2  #y도 계산그래프에 포함이됨 (x에서 requires_grad=True 이렇게 되어 있으므로)
print (y, y.grad_fn)  
z= y*y*3    #x를 계산그래프에 기록되어 있으므로, 연쇄적으로 z, out 도 모두 계산그래프에 기록됨.
out = z.mean()
z, out

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x0000022CCF12FEE0>


(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [24]:
# 딥러닝에서는 기울기를 구하는 것이 가장 중요함.
# 기울기를 구하는 과정을 역전파(backword <-> forward)라 함 -> 기울기 계산

# 최종 결과가 out 에서부터 시작해서 계산그래프를 거꾸로 거슬러 올라가면서 미분의 연쇄법칙을 사용해서 미분값을 계산
# out을 x에 대해서 미분
out.backward()
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [25]:
# out = 1/4(z1+z2+z3+z4)
# z = 3y^2
# y = x + 2

# d-out/dxi =
# chat gpt를 이용해서 미분 연쇄법칙으로 계산해보면 상기 x.grad 와 동일한 4.5 결과값이 나옴

In [ ]:
# 기울기 제어
# 역전파, torch.no_grad, detach
# required_grad =True 연산 추적
import torch
x = torch.randn(3, requires_grad=True)
print(x)
# y는 x로부터 연산기록을 물려받음
y = x*2
y, y.data, y.data.norm() 
# y.data: 텐서의 기록을 무시하고 순수한 데이터만 출력
# norm(노름, 유클리드 노름) : 벡터의 크기를 측정하는 방법 (원점으로부터 벡터까지의 거리) 모든 요소를 각각 제곱하고 모두 더해서 결과에 제곱근(루트)
# y의 실제데이터의 크기를 확인해서 반복 
i=0
while y.data.norm() < 1000:
    y=y*2
    i += 1
print (f'y: {y}')
print (f'반복횟수 : {i} y=x*2^i+1')

# 벡터에 대한 역전파 ( 야코비안 행렬 )
# 벡터를 벡터로 미분하면 결과는 행렬인 야코비안 행렬이라 일컫음.
# pytorch는 전체 야코비안 행렬을 직접 계산하는 대신 야코비안-벡터 곱을 계산해서 메모리를 절약
v=torch.tensor([ 0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)  #y를 x에 대해 미분한 야코비안 행렬과 입력으로 제공된 벡터 v를 곱하라는 의미
print(f'x.grad : {x.grad}')


tensor([-0.6423,  0.7172,  0.0254], requires_grad=True)
y: tensor([-1315.3518,  1468.9279,    52.0052], grad_fn=<MulBackward0>)
반복횟수 : 10 y=x*2^i+1
x.grad : tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


💡 1️⃣ “기울기(Gradient)”가 왜 중요한가?

기울기는 “변화율”, 즉 **“얼마나, 어느 방향으로 바꿔야 더 좋아질지”**를 알려줍니다.

예를 들어볼게요 👇

모델이 예측을 했는데,
“예측값이 정답보다 조금 작다”

이때 우리는
“그럼 가중치를 얼마만큼 늘려야 예측이 맞아질까?”
이걸 알고 싶어요.

👉 **그게 바로 기울기(gradient)**예요.

🧭 2️⃣ “야코비안 행렬”은 어디에 쓰는가?

기울기가 스칼라 → 벡터 관계였다면,
야코비안은 벡터 → 벡터 관계에서의 “기울기”입니다.

```
▶ 스칼라 백워드 (Scalar Backward) : 역전파로 구하는 기울기가 하나일때
out.backwqrd()
최종점수가 숫자하나.  ex) 수학공부 1시간 했을 때 최종점수에 몇점의 영향을 줬는지 
최종목표가 하나 (스칼라)이기 때문에 각 원인(각 변수)의 기여도를 바로 계산 

▶ 벡터 백워드 vector backward : 기울기가 여러개 일 때
y.backward (v)
ex. 과목별(국영수) 점수가 담긴 성적표 (벡터)가 있을 때, 
공부시간이 성적에 얼마나 영향을 줬는지 물어보면 애매함. 국어성적이 오르나? 영어성적이 오르나?
가중치 또는 중요도를 알려주는 벡터 v=torch.tensor([ 0.1, 1.0, 0.0001], dtype=torch.float)
이 중요도를 반영해서 최종적으로 공부시간의 기여도를 확인 
```

In [33]:
x.requires_grad
# 각 학습을 진행하면서 도중에 모델의 성능 평가가 필요 - 기울기 계산을 하면 안됨
with torch.no_grad():   # no_grad 는 기울기를 계산하지 않고, 선택값을 출력?
    print(f'no_grad 내부 : {(x**2).requires_grad}')

# .detach() 계산그래프 
print(f'detach 전 {y.requires_grad}')
y=x.detach()
print(f'detach 후 {y.requires_grad}')


no_grad 내부 : False
detach 전 True
detach 후 False
